name: devtinder-react
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: login into docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name: Build and push
      #   run: |
      #     docker build -t devtinder-react .
      #     docker tag devtinder-react ${{ secrets.DOCKER_USERNAME }}/devtinder-react
      #     docker push ${{ secrets.DOCKER_USERNAME }}/devtinder-react
      
      - name: Docker compose down
        run: docker-compose down
        
      - name: Docker compose up
        run: docker-compose up -d

      - name: docker system prune
        run: docker system prune -a -f


